### ISSUE TITLE
Include option to filter pre/post-exec containers

### ISSUE THREAD

**Issue by Leny1996** [futurice/docker-volume-backup#13]
There should be option in env variable to select container to exec commands.
Now if I have two containers with pre/post-exec labels and I want different scheduling for them, it's calling commands on both of containers when any backup container cron is called.

There are two options:
1. Provide regex expression in environment variable 
2. Provide custom label and then provide labels in service config, like command exec

**Comment by jareware** [comment]
I'm not sure I fully understand the use case... could you give an example?

**Comment by Leny1996** [comment]
Created pull request.
My example:
2 containers - elasticsearch & postgres on the same machine.
I want to backup elasticsearch snapshots everyday, but postgres dump only once a week.
I'm creating two containers based on docker-volume-backup: one for elasticsearch, second for postgres.
Both containers are configured to use docker socket for making backup first.

In that case when any of backup container is launched, both elasticsearch & postgres pre-exec commands are executed.

**Comment by michael-robbins** [comment]
@jareware this would be awesome to get fixed and merged in

Given all volumes are bundled into a single backup, and (at least) my usecase would be to have separate files per volume, I'm running multiple instances of `docker-volume-backup` per service.

But the way the pre/post exec's run, is that each instance of `docker-volume-backup` will trigger the pre/post exec's of all *other* instances, resulting in many rerun's of the pre/post exec.

While this is fine/whatever/not too cumbersome for the time being, it'd be nice if I attached a unique label per service, then be able to filter on that label per instance of `docker-volume-backup` through the PR mentioned here.

I can see why you'd think this is more of a 'hack' around the bigger feature of being able to separate the backup file into a 'per volume' backup file, but it'd be nice to get merged in and built anyway!

**Comment by jareware** [comment]
This is now available as part of [the latest release](https://github.com/futurice/docker-volume-backup/releases/tag/v2.3.0)!

**Comment by Leny1996** [comment]
Thanks @jareware, it will be nice if you could also update README and mention this feature.

**Comment by jareware** [comment]
Oooh, good point, missed the docs update round on that one.

The new `BACKUP_CUSTOM_LABEL` option is now documented on the README.
