### ISSUE TITLE
add restore backup instructions

### ISSUE THREAD

**Issue by gfiasco** [futurice/docker-volume-backup#24]
Hi 

I'm sure I can figure them out but I think would be beneficial to add restore steps in the readme

so people can jump in this git project do an quick test BACKUP/Restore and give it a thumbs up

Cheers 👍

**Comment by jareware** [comment]
Great idea, let's add that to the README. 👍 

If anyone manages a PR, I'll be more than happy to review & merge.

**Comment by jluislval** [comment]
is there an example of this in the meantime?

**Comment by jareware** [comment]
There is now a [detailed example of restoring from S3](https://github.com/futurice/docker-volume-backup#restoring-from-s3).
