### ISSUE TITLE
add option to encrypt the data before storying it to S3

### ISSUE THREAD

**Issue by tcurdt** [futurice/docker-volume-backup#25]
would be really good to have

**Comment by jareware** [comment]
It's a cliché at this point, but: patches are always welcome! 🙏

**Comment by jareware** [comment]
...though as it turns out, this is now available as part of [the latest release](https://github.com/futurice/docker-volume-backup/releases/tag/v2.3.0)! 😄

**Comment by tcurdt** [comment]
That was faster than I was able to comment :-D
