### ISSUE TITLE
awscli v2 break raspberry pi usage

### ISSUE THREAD

**Issue by caiych** [futurice/docker-volume-backup#29]
Since this commit https://github.com/futurice/docker-volume-backup/commit/074f2e7e167d5231741187918a8e9d2d208bdac9, the cli the image is using rolled forward to v2.

This image no longer works on raspberry pi.

I verified this by checking out v2.1.0 tag and rebuild the image locally -> working.
checking out v2.3.0 tag and rebuild the image locally -> `./backup.sh: line 95: /usr/bin/aws: cannot execute binary file: Exec format error`

Is there a particular reason to move to v2 already? Maybe wait for AWS to release them in package manager? ref: https://github.com/aws/aws-cli/issues/4947#issuecomment-793192340

---
Docker hub doesn't have an arm build is also a problem but I guess I'll save it for now. (is it #5?)

---
BTW thanks for this great repo, I've researched a bit and by far this is the most satisfying despite the arm related issue.

**Comment by jareware** [comment]
Thanks for the feedback, happy to hear!

The original reason for bumping to v2 was #19. And I can see why having Glacier support is nice, when it's backups we're talking about.

But also I'd love to keep supporting the Pi use case.

Would welcome any PR's fixing this.

**Comment by jan-brinkmann** [comment]
> Would welcome any PR's fixing this.
Here it comes: https://github.com/futurice/docker-volume-backup/pull/34

**Comment by jareware** [comment]
Fixed by #34.

I'll make a release soon.
