### ISSUE TITLE
Cron is always in UTC

### ISSUE THREAD

**Issue by ipatalas** [futurice/docker-volume-backup#4]
Hi,

thanks for great tool but I found out there is a small problem with setting cron expressions. I'm in UTC+2h and have set the backup to run at 4 AM. 
I've also set up Influx metrics and found out that it actually runs at 6 AM instead of 4 AM. Timestamps of created backups confirm it's 6 AM.
After a while I've figured out that the container is running always in UTC timezone (looks like it's a Docker default - my other containers run on UTC as well). Not a big deal for people in Europe but imagine someone in Australia thinking his backups are created at night while in fact they are created in the middle of the day.

Anyone got the same? (see the results of ` docker exec -it <container_name> date` command)

**Comment by ipatalas** [comment]
All right... I digged a little and found the easiest solution possible.
It's just the matter of setting TZ environment variable to your timezone.

Command line: 
`docker run -e TZ=America/New_York [...]`

Docker compose:
```yml
environment:
      TZ: Europe/Warsaw
```

You can get the list of available timezones [here](http://manpages.ubuntu.com/manpages/bionic/man3/DateTime::TimeZone::Catalog.3pm.html)

**Comment by jareware** [comment]
This indeed should be included in the README, thanks a lot!
