### ISSUE TITLE
[Feature] Keep last n versions or versions of last n days

### ISSUE THREAD

**Issue by sontd-0882** [futurice/docker-volume-backup#7]
Hi!

Thanks for a great tool.
I think it would be nice if you can implement a new feature allows cleaning up old backups.
Maybe keep last n backups or keep the backups of last n days, something like that.

Thank you.

**Comment by breuerfelix** [comment]
https://github.com/xolox/python-rotate-backups

this is reeeaaallly simple and straight forward. i use volume backup + this tool for my backup retention :)

**Comment by jareware** [comment]
I would perhaps agree that an external utility would be a better fit here, to keep this project as simple as possible.

I'll make sure to update the README with this tip, though!
