### ISSUE TITLE
Ability to execute once immediately

### ISSUE THREAD

**Issue by chasdevs** [futurice/docker-volume-backup#8]
Some workflows may want to execute the backup once immediately as opposed to on a cron schedule. I didn't see a way to do this as-is, but seems like it could be pretty easy to configure via an alternative entrypoint, or configuring the entrypoint to only do the initialization and then defaulting to the cron command but allowing an override command.

**Comment by jareware** [comment]
This would be a great addition!

I'll update the README with instructions for this.
