### ISSUE TITLE
Filename is always the same

### ISSUE THREAD

**Issue by BacLuc** [futurice/docker-volume-backup#9]
https://github.com/futurice/docker-volume-backup/blob/96b702cbf1af642d0b96b6bfbea104141863fe04/src/entrypoint.sh#L11

Because the entrypoint.sh is only executed at startup, the filename used is always the same.
Only the Pattern for the date format should be saved, and then evaluated when the new backup file is created.

I will submit a PR soon.

**Comment by breuerfelix** [comment]
hey,

this repo seems pretty inactive thats why i maintained my fork of it and i also fixed this bug over there with some other useful stuff

https://github.com/breuerfelix/docker-volume-backup

**Comment by jareware** [comment]
Sorry for dropping the ball on this; for whatever reason I hadn't subscribed to notifications on this repo, even though I'm the maintainer. :facepalm: 

@breuerfelix feel free to send PR's for your improvements, this time I'll notice them!

**Comment by jareware** [comment]
Merged in #10, thanks for the fix @BacLuc!

**Comment by breuerfelix** [comment]
@jareware i will try to reopen my PR once i got some time ! :) since i am currently not using it it is hard to find some time :D
